# Generated by Django 4.2 on 2023-06-15 20:28

from django.db import migrations
import news.custom_field


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_feed_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'Feed'},
        ),
        migrations.AlterField(
            model_name='article',
            name='special',
            field=news.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_homepage',
            field=news.custom_field.CustomBooleanField(),
        ),
    ]
